### ISSUE TITLE
Media Optimization

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#2214]
This is a tracking issue for media optimization-related tasks

- [x] #2212 
- [x] #2098 
- [x] #1717 

Transcoding/video uploads:

- [ ] https://github.com/damus-io/damus/issues/2357
- [x] https://github.com/damus-io/damus/issues/2220
- [ ] https://github.com/damus-io/damus/issues/2219
- [ ] https://github.com/damus-io/damus/issues/2217
- [ ] https://github.com/damus-io/damus/issues/2218
- [x] https://github.com/damus-io/damus/issues/2216

@fishcakeday has been doing some work on the nostr.build side, so we shouldn't try to overlap work where we don't need to. Even is that case, we should still be looking at optimizations for non-nostr-build media sources via proxies.

**Comment by jb55** [comment]
@fishcakeday thanks I broke these into tickets for tracking

**Comment by alltheseas** [comment]
customer feedback on playback UX: https://github.com/damus-io/damus/issues/2422

**Comment by alltheseas** [comment]
Closing as part of a backlog triage — we're narrowing focus to the most actionable issues to reduce noise for contributors.

If this is still relevant, please reopen with updated context or reproduction steps. Thanks for reporting!
