### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#2225]
This is a tracking issue to get push notifications out the door

- [ ] https://github.com/damus-io/damus/issues/1704 (Absolutely necessary)
- [ ] https://github.com/damus-io/damus/issues/1701 (Nice to have, but we already have code we can reuse for this from Damus Purple)
- [ ] https://github.com/damus-io/damus/issues/1706 (Probably needed, but I am not a legal expert to know for sure)
- [ ] https://github.com/damus-io/damus/issues/1707 (We should at least test to see if current behaviour is acceptable)
- [ ] https://github.com/damus-io/damus/issues/1733 (Absolutely necessary)
- [ ] https://github.com/damus-io/damus/issues/2200 (New one that I added, which will be necessary to execute this new plan)

**Comment by alltheseas** [comment]
What is the dependency on waiting for permissions from apple @danieldaquino ?

**Comment by alltheseas** [comment]
> What is the dependency on waiting for permissions from apple @danieldaquino ?

Do we have an issue for tracking the apple permissions?

@jb55 cc @danieldaquino meta-comment on issue of issues tracking: I re-arranged the issues to having the pre-requisite/mandatory tickets at the top, and the nice-to-haves and/or uncertain tickets towards the bottom. If yall agree we can carry forward  this practice for issues of issues.

We can also carry forward this practice for milestones - most important issues at top, least at bottom.

**Comment by danieldaquino** [comment]
@alltheseas

> What is the dependency on waiting for permissions from apple @danieldaquino ?

For this particular plan, none. Here is an excerpt of an email containing relevant context:

> (...) we might be able to roll it out whether or not we have the Push notification filtering entitlement.
>
> Will mentioned that we do not yet have support for encrypted mute lists (we don’t create them, and we do not parse them either).
> 
> Since we do not have support for that yet (Most mute lists on Damus are presumably public), we can perform mute filtering on the server-side based on those public lists (without worsening user’s privacy). If we do that, then having the entitlement does not make a difference until we have encrypted mute lists.
> 
> Given that state of affairs, Will mentioned it will be worth rolling out that feature regardless of whether we get the entitlement or not.

**Comment by danieldaquino** [comment]
> most important issues at top, least at bottom.

Love it, 100% agree we should use that convention

**Comment by alltheseas** [comment]
bumping to current sprint based on previous standup discussion with @danieldaquino

**Comment by danieldaquino** [comment]
I setup the server and published a testflight to start testing push notifications in a real environment.

It seems to be working in some occasions, but alas I am hitting a "PayloadTooLarge" error frequently. It seems that we might be hitting a [4KB payload limit](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html)

**Comment by alltheseas** [comment]
![image](https://github.com/damus-io/damus/assets/64376233/fb8ca602-8e66-4dac-8981-4b98e4924781)

Reply with a quote note mentioned

**Comment by alltheseas** [comment]
Update settings to reflect push notifications![image](https://github.com/damus-io/damus/assets/64376233/f875046f-849c-494a-8bcf-ef368c439d11)

**Comment by jb55** [comment]
> I setup the server and published a testflight to start testing push notifications in a real environment.
> 
> It seems to be working in some occasions, but alas I am hitting a "PayloadTooLarge" error frequently. It seems that we might be hitting a [4KB payload limit](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html)

I'm guessing because its sending kind3 events anytime someones contact list changes. I get spammed with these (for smaller lists). we should fix that.

**Comment by jb55** [comment]
multi-device seems to work!

**Comment by jb55** [comment]
btw I definitely have the profile in nostrdb but the push notification still says "someone zapped you".

**Comment by danieldaquino** [comment]
Spent a few hours (about 2~3 h) trying to port the plugin logic to Rust. I could not get it to work in this time, but I was able to port a "skeleton" over and solve a lot of compiler issues. In the end there are still a significant amount of compiler issues to resolve, but I think it's reasonable to keep going at it, it seems promising.

My WIP draft so far: https://github.com/danieldaquino/noteguard/commit/477cb6dd4d5e13c88271927c3b049195640efe7f (does not fully compile yet)

**Comment by danieldaquino** [comment]
> Spent a few hours (about 2~3 h) trying to port the plugin logic to Rust. I could not get it to work in this time, but I was able to port a "skeleton" over and solve a lot of compiler issues. In the end there are still a significant amount of compiler issues to resolve, but I think it's reasonable to keep going at it, it seems promising.
> 
> My WIP draft so far: [danieldaquino/noteguard@477cb6d](https://github.com/danieldaquino/noteguard/commit/477cb6dd4d5e13c88271927c3b049195640efe7f) (does not fully compile yet)

@jb55 if you agree this looks like the best way to go, I can create a ticket so that I can work on it further

**Comment by jb55** [comment]
On Mon, Jul 08, 2024 at 06:09:58PM GMT, Daniel D’Aquino wrote:
>Spent a few hours (about 2~3 h) trying to port the plugin logic to Rust. I could not get it to work in this time, but I was able to port a "skeleton" over and solve a lot of compiler issues. In the end there are still a significant amount of compiler issues to resolve, but I think it's reasonable to keep going at it, it seems promising.
>
>My WIP draft so far: https://github.com/danieldaquino/noteguard/commit/477cb6dd4d5e13c88271927c3b049195640efe7f (does not fully compile yet)

thanks! I'll take a look and start hacking on it.

**Comment by jb55** [comment]
On Tue, Jul 09, 2024 at 08:30:02AM GMT, William Casarin wrote:
>On Mon, Jul 08, 2024 at 06:09:58PM GMT, Daniel D’Aquino wrote:
>>Spent a few hours (about 2~3 h) trying to port the plugin logic to Rust. I could not get it to work in this time, but I was able to port a "skeleton" over and solve a lot of compiler issues. In the end there are still a significant amount of compiler issues to resolve, but I think it's reasonable to keep going at it, it seems promising.
>>
>>My WIP draft so far: https://github.com/danieldaquino/noteguard/commit/477cb6dd4d5e13c88271927c3b049195640efe7f (does not fully compile yet)
>
>thanks! I'll take a look and start hacking on it.

I've rebased it onto the apns branch, I am working on it there

**Comment by jb55** [comment]
On Mon, Jul 08, 2024 at 06:11:38PM GMT, Daniel D’Aquino wrote:
>> Spent a few hours (about 2~3 h) trying to port the plugin logic to Rust. I could not get it to work in this time, but I was able to port a "skeleton" over and solve a lot of compiler issues. In the end there are still a significant amount of compiler issues to resolve, but I think it's reasonable to keep going at it, it seems promising.
>>
>> My WIP draft so far: ***@***.***(https://github.com/danieldaquino/noteguard/commit/477cb6dd4d5e13c88271927c3b049195640efe7f) (does not fully compile yet)
>
>@jb55 if you agree this looks like the best way to go, I can create a ticket so that I can work on it further

I think a better approach is to have a noteguard filter that is
basically a "forwarder". a way to write notes over a socket/websocket to
somewhere else.

This would allow us to set up an APNs daemon/relay that doesn't care
about the details, traits, or run lifetime of noteguard. We just need to
make sure the forwarder reconnects, etc.

The cool thing about a notification relay is that it wouldn't need to
write to disk, so people could push private events to it. It could be
anywhere. We could also run it on a different server and have a
standalone endpoint that people could push events to:

https://notify.relay.damus.io

although we might want to put noteguard in front of that as well for
rate limiting, lol.

We also wouldn't have to worry about encryption on the endpoint that 
receives the device tokens, as it could be a part of the same server.

I am hacking on noteguard today so I can put together a forwarder
filter.

**Comment by danieldaquino** [comment]
@jb55 I got notepush to work, with some intermittent issues that I am trying to fix. Latest runnable code is pushed to `master` on the notepush repo! I will keep fixing remaining issues

**Comment by jb55** [comment]
On Wed, Jul 31, 2024 at 02:47:44PM -0700, Daniel D’Aquino wrote:
>@jb55 I got notepush to work, with some intermittent issues that I am trying to fix. Latest runnable code is pushed to `master` on the notepush repo! I will keep fixing remaining issues

awesome, I'll take a look!

**Comment by danieldaquino** [comment]
@jb55, updates on notepush:
- Fixed the intermittent issues I was facing. It feels stable now from local testing!
- Changed mutex architecture to dramatically improve performance potential and reduce shared resource contention
- Fixed an issue where it would never format
- Merged your Cargo formatting PR.
- Improved notification fallback formatting (Probably addresses https://github.com/damus-io/damus/issues/2323)
- Stopped sending notifications for random nostr event kinds (should address https://github.com/damus-io/damus/issues/2322)

We reached (and passed) feature parity with the previous Deno solution! strfry-push-notify is obsolete

**Comment by danieldaquino** [comment]
@jb55 forgot one:
- Unified Web API and Websockets interface. Now both the API and the websockets relay can be accessed through the same port without issues

All code is pushed to `master` in notepush

**Comment by danieldaquino** [comment]
@alltheseas @jb55, after https://github.com/damus-io/damus/issues/2360 is closed, I suggest that we try deploying and rolling out an internal testflight for internal testing. As all server-side code was completely rewritten, the list of issues in the description may have changed significantly.

**Comment by danieldaquino** [comment]
@alltheseas @jb55 I am configuring a notepush deployment on our servers for testing. I will post more updates in this ticket soon

**Comment by danieldaquino** [comment]
Actually I will post updates on deployment on https://github.com/damus-io/damus/issues/2384 😅

**Comment by danieldaquino** [comment]
**2024-09-02 updates on push notifications:**
- Deployed staging push notification environment which can be used with dev builds
- Sent a PR that allows damus to connect with the staging environment or with a custom notepush server: https://github.com/damus-io/damus/pull/2415/commits
- Sent a PR that should fix #2403: https://github.com/damus-io/damus/pull/2416
- Sent a notepush PR with 3 fixes/improvements: https://github.com/damus-io/notepush/pull/6
    - I already deployed these changes on our server (for prototype testing)
- @jb55 if you have a chance to use the new staging environment with a local build and debugger, can you please let me know about the error logs/error codes you are seeing on the push notification extension?

CC @jb55 @alltheseas

**Comment by jb55** [comment]
> * @jb55 if you have a chance to use the new staging environment with a local build and debugger, can you please let me know about the error logs/error codes you are seeing on the push notification extension?

I'll test this today

**Comment by danieldaquino** [comment]
> > * @jb55 if you have a chance to use the new staging environment with a local build and debugger, can you please let me know about the error logs/error codes you are seeing on the push notification extension?
> 
> I'll test this today

@jb55 were you able to get some info on the error codes/logs you are seeing on the extension?

**Comment by alltheseas** [comment]
Continue to receive generic reactions on 1.10 with onlyzaps on

**Comment by alltheseas** [comment]
Continue to receive someone zapped you 1.10 ;8) ![image](https://github.com/user-attachments/assets/ceb84833-820a-4fe3-8649-3cd8eeca74fb)

**Comment by danieldaquino** [comment]
I suspect @alltheseas's issue might be related to having a large NostrDB database file. I have no evidence yet, but just a gut feel — I can't imagine another reason at the moment. I opened a ticket to track this: https://github.com/damus-io/damus/issues/2437

**Comment by alltheseas** [comment]
Behavior from today

![image](https://github.com/user-attachments/assets/c56a976b-5584-490b-9891-03cdac9a1e89)

**Comment by alltheseas** [comment]
Latest behavior is improved! ![image](https://github.com/user-attachments/assets/5159360b-bd0d-4bf2-bce3-7f7ce4758574)

![image](https://github.com/user-attachments/assets/55239f17-50c4-45ed-8083-c28bafd0d3fd)

![image](https://github.com/user-attachments/assets/51d864b6-7c17-4479-84c5-107e75e06668)

Only reactions remain without name of who is reacting

**Comment by danieldaquino** [comment]
The team decided that push notifications are in good shape for the 1.10 release. This ticket will remain open to track other improvements to push notifications, but will be descoped from the 1.10 milestone

**Comment by alltheseas** [comment]
![image](https://github.com/user-attachments/assets/097351bd-56fe-4bb9-adde-bf611945554a)

https://damus.io/nevent1qqsr2vj029nq6xjem26m3ef0uwau2y5h5rt98yhzmgug7qxp2zxeu2cpz4mhxue69uhk2er9dchxummnw3ezumrpdejqzyrhwden5te0dehhxarj9emkjmn9qythwumn8ghj7enfd36x2u3wdehhxarj9emkjmn9qyv8wumn8ghj7un9d3shjtnndehhyapwwdhkx6tpdsxj45ys

**Comment by alltheseas** [comment]
added customer reported muted user push notification unexpected behavior https://github.com/damus-io/damus/issues/2574

**Comment by alltheseas** [comment]
Closing as part of a backlog triage — we're narrowing focus to the most actionable issues to reduce noise for contributors.

If this is still relevant, please reopen with updated context or reproduction steps. Thanks for reporting!
