### ISSUE TITLE
Low data mode tracking

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2226]
- [ ] #1838 (it would be useful to understand data demands & behavior - note loading, PFP, profile banner, media, one relay, few relays, many relays etc)
- [ ] https://github.com/damus-io/damus/issues/919 (validated)
- [ ] #2098 (planned)
- [ ] https://github.com/damus-io/damus/issues/2227 (unvalidated)
- [ ] too many relays warning https://github.com/damus-io/damus/issues/544
- [ ] time/MB remaining UI https://github.com/damus-io/damus/issues/2485
- [x] https://github.com/damus-io/damus/issues/2739

### tangential
- [ ] embed Tor https://github.com/damus-io/damus/issues/2465

**Comment by alltheseas** [comment]
added embed tor to low data mode tracker as bonus points

**Comment by alltheseas** [comment]
suggested by @tyiu - Damus should populate notes from nostrdb first in no/limited connectivity https://github.com/damus-io/damus/issues/2739

**Comment by alltheseas** [comment]
Closing as part of a backlog triage — we're narrowing focus to the most actionable issues to reduce noise for contributors.

If this is still relevant, please reopen with updated context or reproduction steps. Thanks for reporting!
