### ISSUE TITLE
iOS18 Issues

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#2371]
This is a tracking issue for all of the issues in iOS18. Most of them are super annoying.

- [x] https://github.com/damus-io/damus/issues/2583
- [x] https://github.com/damus-io/damus/issues/2458
- [x] #2577
- [ ] #2578
- [x] https://github.com/damus-io/damus/issues/2342
- [x] #2366 
- [x] #2359 
- [x] https://github.com/damus-io/damus/issues/2370
- [x] https://github.com/damus-io/damus/issues/2373
- [x] https://github.com/damus-io/damus/issues/2393
- [x] https://github.com/damus-io/damus/issues/2460
- [x] https://github.com/damus-io/damus/issues/2496

**Comment by Kasucode101** [comment]
@iOS version iOS performance and pre install software verification not only for developers technical but also users non technical is feedback gap on technical gap that big tech exploit beyond privacy that needs platforms on continuous feedback on software performance unlike hardware performance using user manual and user incentive allocation to finance/support exit strategy beyond supply chain problems on demand.

**Comment by tkhumush** [comment]
Did see you are tracking here. 

I just added Video Media Control on iOS18. 

Seems like a low hanging fruit.

**Comment by alltheseas** [comment]
Added @tkhumush missing vid controls ios 18 to tracker

**Comment by alltheseas** [comment]
Not good: relay / network connectivity is suffering on iOs 18 1.10

https://github.com/damus-io/damus/issues/2496

**Comment by jb55** [comment]
@danieldaquino ship it!
