### ISSUE TITLE
Counter / persistence tracker

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2433]
- [ ] https://github.com/damus-io/damus/issues/1657

- [ ] https://github.com/damus-io/damus/issues/641

- [ ] https://github.com/damus-io/damus/issues/1389

- [ ] https://github.com/damus-io/damus/issues/2150

- [ ] https://github.com/damus-io/damus/issues/1926

- [ ] https://github.com/damus-io/damus/issues/884

**Comment by alltheseas** [comment]
Vanessa reported not seeing zaps.

Im experiencing the same.

Making note to revisit post connectivity fix update.

**Comment by alltheseas** [comment]
@danieldaquino is ambitious - adding to current sprint

https://media.tenor.com/Sea2NTqNI1gAAAAC/arnold-schwarzenegger-muscles.gif

**Comment by alltheseas** [comment]
to follow video fixes, and iOS 18 sensitivity fixes

**Comment by alltheseas** [comment]
Counter in feed vs in note view

![image](https://github.com/user-attachments/assets/b8fa707a-6159-4d2d-8310-43371c15c564)

![image](https://github.com/user-attachments/assets/e57dd96f-95d9-4524-8a31-66281bf817b5)

**Comment by alltheseas** [comment]
added suggeted hashtag numbers seem off https://github.com/damus-io/damus/issues/2726

**Comment by alltheseas** [comment]
added incorrect re-post count in re-post view https://github.com/damus-io/damus/issues/2740

**Comment by alltheseas** [comment]
@danieldaquino see note1qqqdxg600eakrxhckg9yff43mtfm75h9em4mewm9apepypssr92qksz54t

And 

https://github.com/nostr-protocol/nips/pull/1561

**Comment by alltheseas** [comment]
Closing as part of a backlog triage — we're narrowing focus to the most actionable issues to reduce noise for contributors.

If this is still relevant, please reopen with updated context or reproduction steps. Thanks for reporting!
