### ISSUE TITLE
1.11 bugs / improvements

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2594]
###  Bugs in (and not exclusively in 1.11)
- [ ] Cannot swipe in image carousel (@danieldaquino thinks its iOS 18 #2371 ; posisbly kingfisher iOS 18 related issue) see note1gje3hgfxlwsr7nql2hmu48vh2nzjrplhrd7fegadqa0dga0msgvqjfkrk7. Sometimes works, sometimes doesn't.
- [ ] https://github.com/damus-io/damus/issues/2472 (this is 1.10, and also 1.9 issue)
- [x] When i zoom into an image I cannot move from side to side. See note184w032dl0klgm6zzudfwupw5tz0n3qhu97z46ur88wqeclqjrheqdk7lp4 (yesterday it did not work. now it works ???)
- [ ] Auto zoom out post zoom in 
- [x] Post button doesn't work after it disappears (still there, but cant click on post button)
- [ ] Bottom nav disappears https://github.com/damus-io/damus/issues/2697
- [x] Opacity of bottom nav during/after scroll
- [x] Crowded padding in universe view @ericholguin to investigate

### not necessarily an 1.11 bug

- [ ] Cannot long hold tap to save an image (from timeline, or selected note; only avaialble when image is open)

![image](https://github.com/user-attachments/assets/69b764ba-3a5f-466a-8dcc-5674c200f49b)

![image](https://github.com/user-attachments/assets/f7978b7f-1ce5-4010-b678-9475edffe0a7)

**Comment by alltheseas** [comment]
Added cannot long hold tap to save image

**Comment by alltheseas** [comment]
A couple image related bugs

**Comment by alltheseas** [comment]
Adding auto zoom back out https://damus.io/nevent1qqs9hyvwpcc3m03aa6nj74gsah2ey224lxpt0ggktq4gk520uzv0wvqpzemhxue69uhhyetvv9ujumn0wvh8xmmrd9skcqgdwaehxw309ahx7uewd3hkcqgewaehxw309ac8junpd45kgtnxd9shg6npvchxxmmdqyt8wumn8ghj7un9d3shjtnwdaehgu3wvfskuequ9d7xl

**Comment by alltheseas** [comment]
Bottom nav disappears due to some unknown combination of safari highlight, replying to notes

![image](https://github.com/user-attachments/assets/9167aade-d356-40d6-8433-f8ae17365d58)

**Comment by alltheseas** [comment]
see inline video - unmute it - it will open up thread. doesnt register click on mute button from @jb55

**Comment by alltheseas** [comment]
@jb55 shared https://damus.io/nevent1qqs2rzqtuhnaldnghfjk8mr6ct9p6qjxae4wsk43wp4p46lhx559laqpp4mhxue69uhkummn9ekx7mqpp3mhxue69uhkyunz9e5k7qg5waehxw309aex2mrp0yhxgctdw4eju6t0qy28wumn8ghj7un9d3shjtn90p5hgtnsw43q3vwemw does not open to carousel

cc @danieldaquino

**Comment by alltheseas** [comment]
https://github.com/damus-io/damus/pull/2607

**Comment by alltheseas** [comment]
Marked "When i zoom into an image I cannot move from side to side" as fixed.

Added missing bottom nav issue link https://github.com/damus-io/damus/issues/2697
