### ISSUE TITLE
Onboarding improvements tracker

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2642]
### General

- [x] https://github.com/damus-io/damus/issues/2635
- [x] https://github.com/damus-io/damus/issues/2771
- [x] https://github.com/damus-io/damus/issues/2744
- [x] https://github.com/damus-io/damus/issues/2643
- [x] https://github.com/damus-io/damus/issues/2636
- [ ] Test @scoder1747 PFP upload fix (@jb55 advised merged code, and not yet tested)

### Low data/performance/reliability improvements

- [ ] https://github.com/damus-io/damus/issues/2637
- [ ] npub123 does not resolve to a name (appears as gibberish to a new user) https://github.com/damus-io/damus/issues/1584
- [ ] https://github.com/damus-io/damus/issues/2283

### In person/conference 

- [ ] https://github.com/damus-io/damus/issues/2395

### immediate post onboarding improvements

- [ ] search tab design https://github.com/damus-io/damus/issues/2602

### Post-onboarding/discoverability

- [x] https://github.com/damus-io/damus/issues/1645

### technical

- [ ] https://github.com/damus-io/damus/issues/2698

### Future/advanced/bonus points
- [ ] https://github.com/damus-io/damus/issues/2672
- [x] https://github.com/damus-io/damus/issues/1696
- [ ] https://github.com/damus-io/damus/issues/2732
- [x] https://github.com/damus-io/damus/issues/1748
- [ ] https://github.com/damus-io/damus/issues/1776
- [ ] #1302 
- [ ] https://github.com/damus-io/damus/issues/1785
- [ ] #2641 
- [ ] https://github.com/damus-io/damus/issues/987
- [ ] #2134 
- [ ] #1864 
- [ ] https://github.com/damus-io/damus/issues/2127 WOT score rank: HMW apply a WOT indicator for people new to nostr, with no frame of reference of high quality npubs vs spam/bot npubs?
- [x] https://github.com/damus-io/damus/issues/2238
- [x] #1623 
- [x] https://github.com/damus-io/damus/issues/571

**Comment by alltheseas** [comment]
@ericholguin

**Comment by alltheseas** [comment]
Added post-onboarding/discoverability section, as "onboarding" is not one and done. I view onboarding as a continuous process.

**Comment by alltheseas** [comment]
adding damoose signer https://github.com/damus-io/damus/issues/2238

**Comment by alltheseas** [comment]
Linked name does not render/npub gibberish is displayed instead of name

https://github.com/damus-io/damus/issues/1584

**Comment by alltheseas** [comment]
adding the daniel's onboarding/personalized onboarding: https://github.com/damus-io/damus/issues/1696 

cc @danieldaquino check this one out

**Comment by alltheseas** [comment]
Added broken nwc onboarding https://github.com/damus-io/damus/issues/2744

**Comment by alltheseas** [comment]
Added loading https://github.com/damus-io/damus/issues/2283

**Comment by alltheseas** [comment]
Added https://github.com/damus-io/damus/issues/2771

**Comment by danieldaquino** [comment]
> Test @scoder1747 PFP upload fix (@jb55 advised merged code, and not yet tested)

@alltheseas, which fix does this refer to? I may have tested this as part of my work on some of these onboarding fixes, depending on what this refers to

**Comment by alltheseas** [comment]
Closing as part of a backlog triage — we're narrowing focus to the most actionable issues to reduce noise for contributors.

If this is still relevant, please reopen with updated context or reproduction steps. Thanks for reporting!
